name: anad_magicar
description: Anad MagiCar App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+1

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    magicar: # Flavor Name
      app:
        name: "Magicar" # Application Name

      android:
        applicationId: "com.magicar" # Package Name

      ios:
        bundleId: "com.magicar"
    adora:
      app:
        name: "Adora"

      android:
        applicationId: "com.adora"
      ios:
        bundleId: "com.adora"
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  firebase_auth_web:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  scoped_model: ^1.0.1
  dwds: any

  url_launcher_web: ^0.1.2

  intl: ^0.15.7
  intl_translation: ^0.17.7


  flutter_custom_clippers: ^1.0.4
  #sqflite: ^1.1.6+3
  path_provider: any

  #angel_framework: ^2.0.4+1
  #angel_orm: ^2.0.1
  #angel_orm_generator: ^2.0.5
  #angel_migration: ^2.0.0


  provider: ^4.0.0
  file: ^5.0.7

  #jaguar_orm: ^2.2.6

  bottom_navy_bar: ^2.2.0
  after_layout: ^1.0.7+2
  #catcher: ^0.0.6

  dio: any
  flutter_web_image_picker: ^0.0.2
  image_picker: ^0.6.2+3
  video_player: 0.10.5
  bloc: ^2.0.0
  flutter_bloc: ^2.1.1
  equatable: ^1.0.1
  rxdart: ^0.16.0

  #f_orm_m8: ^0.8.0+3

  cached_network_image: ^2.0.0
  transparent_image: ^1.0.0
  #flutter_advanced_networkimage: any
  package_info: ^0.4.0+13
  device_info: ^0.4.1+4
  floating_search_bar: ^0.2.0
  uuid: ^2.0.4
  build_runner: ^1.0.0
  #jaguar_orm_gen: ^2.2.27
  #jaguar_query_sqflite: ^2.2.10
  shared_preferences_web: ^0.1.0
  #flutter_uploader: ^1.2.0
  fluttertoast: ^7.1.4
  progress_dialog: ^1.2.0
  flutter_map: ^0.10.1+1
  #map_controller: any
  #mapbox_gl: ^0.0.5
  local_auth: ^0.6.1
  get_it: ^3.0.3
  #install_plugin: ^2.0.1
  permission_handler: ^4.0.0
  connectivity: ^0.4.6+1
  avatar_glow: ^1.1.0
  flutter_spinkit: ^4.1.1+1
  #sider_bar: ^0.1.1
  location: ^3.0.2
  #mapbox_gl:
  #path: ./flutter-mapbox-gl
  liquid_swipe: ^1.3.0
  simple_animations: ^2.4.2
  sliding_up_panel: ^0.3.6
  flutter_swiper: ^1.1.6
  transformer_page_view: ^0.1.6
  solid_bottom_sheet: ^0.1.9
  audioplayers: ^0.13.5
  cookie_jar: ^1.0.1
  #assets_audio_player: ^1.0.1
  flutter_typeahead: ^1.8.3
  sy_flutter_widgets: ^0.1.4
  #flutter_chips_input: ^1.8.3
  datetime_picker_formfield: ^0.4.3
  validators: ^2.0.0+1
  date_range_picker: ^1.0.6
  font_awesome_flutter: ^8.5.0
  #flushbar: ^1.9.1
  auto_size_text: ^2.1.0
  image: ^2.1.4
  #livemap: ^0.6.0
  speech_bubble: ^0.0.6
  requests: ^3.3.0
  #flutter_datetime_picker: ^1.3.1
  firebase_core: ^0.4.4+3
  firebase_messaging: ^6.0.15
  firebase_auth: ^0.16.0
  #cloud_firestore: ^0.13.5
  #slide_button: ^0.2.8
  #flutter_local_notifications: ^0.8.4
  expandable: ^4.0.1
  #flutter_local_notifications: ^0.9.1+3
  pedantic: ^1.7.0
  extra_pedantic: ^1.1.1+3
  meta: ^1.1.7
  geopoint: ^0.7.0
  iso: ^0.3.0
  geodesy: ^0.3.2
  #user_location: ^0.1.0
  #flutter_compass: ^0.3.4
  #eva_icons_flutter: ^2.0.0
  extended_navbar_scaffold: ^1.0.1
  #flutter_vector_icons: ^0.2.0
  mask_text_input_formatter: ^1.0.6
  flutter_masked_text: ^0.8.0
  url_launcher: ^5.7.10
  #android_alarm_manager: ^0.4.5+4
  latlong: ^0.6.1
  geolocator: ^5.3.0
  geolocation: ^1.1.2
  #flutter_mapbox_navigation: ^0.0.10
  flutter_money_formatter: ^0.8.3
  popup_menu: ^1.0.5
  #geojson: ^0.8.0
  vibration: ^1.2.4
  flutter_full_pdf_viewer: ^1.0.6
  maps_toolkit: ^1.0.1+3
  #sa_stateless_animation: ^1.1.0
  flutter_keyboard_visibility: ^2.0.0
  #screen_state: ^0.1.1
  #flutter_svg: any
  universal_io: ^1.0.1
  http_client: ^1.4.1
  share: ^0.6.5+4
  screenshot: ^0.2.0
  universal_platform: ^0.1.3
  #build_web_compilers: ^2.15.2
  #build_daemon: ^2.1.0
  flutter_webview_plugin: ^0.3.11
  #google_maps: any
  #easy_google_maps: ^1.0.0+2
  #easy_web_view: any
  #map_launcher: any
  flutter_svg: ^0.19.1
  worker_manager: ^3.1.6
  great_circle_distance: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_flavorizr: ^1.0.9
  flutter_launcher_icons: ^0.7.2
  simple_animations: ^2.4.2

  #flutter_web: any
  #flutter_web_ui: any
  #google_maps: ">=3.0.0 <4.0.0"
  #build_runner: ^1.6.2
  #map_launcher: any

  # mapbox_gl:
  #   path: flutter-mapbox-gl

flutter_icons:
  android: true
  ios: true

dependency_overrides:
  #analyzer: ^0.38.4
  rxdart: ^0.23.1
  intl: ^0.16.0
  dio: ^3.0.7
  #map_controller: ^0.8.0
  flutter_map: ^0.10.1+1
  #flutter_advanced_networkimage: ^0.7.0
  #cached_network_image: ^2.0.0-rc
  #fluttertoast: ^7.1.1
  flutter_keyboard_visibility: ^3.0.0
  location: ^3.0.2
  #flutter_svg: ^0.19.2+1
  provider: ^3.2.0
  # mapbox_gl_platform_interface:
  #   path: flutter-mapbox-gl/mapbox_gl_platform_interface
  # mapbox_gl_web:
  #   path: flutter-mapbox-gl/mapbox_gl_web
  #flushbar: ^1.9.1
  #flutter_local_notifications: ^0.9.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/iran_sans.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/adora/
    - assets/car_door_lock.mp3
    - assets/img/bg/
    - assets/images/
    - assets/trunk_close.mp3
    - assets/door_open.mp3
    - assets/car_door_close.mp3
    - assets/car_door_open.mp3
    - assets/start_engine.mp3
    - assets/start_power.mp3
    - assets/open_trunk.mp3
    - assets/lock.mp3
    - assets/off.mp3
    - assets/help.pdf
    - assets/points.txt
    - assets/style.json




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
